// Code generated by ent, DO NOT EDIT.

package statuspagemonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the statuspagemonitor type in the database.
	Label = "status_page_monitor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatusPageID holds the string denoting the status_page_id field in the database.
	FieldStatusPageID = "status_page_id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldSendURL holds the string denoting the send_url field in the database.
	FieldSendURL = "send_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeStatusPage holds the string denoting the status_page edge name in mutations.
	EdgeStatusPage = "status_page"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// Table holds the table name of the statuspagemonitor in the database.
	Table = "status_page_monitors"
	// StatusPageTable is the table that holds the status_page relation/edge.
	StatusPageTable = "status_page_monitors"
	// StatusPageInverseTable is the table name for the StatusPage entity.
	// It exists in this package in order to avoid circular dependency with the "statuspage" package.
	StatusPageInverseTable = "status_pages"
	// StatusPageColumn is the table column denoting the status_page relation/edge.
	StatusPageColumn = "status_page_id"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "status_page_monitors"
	// MonitorInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorInverseTable = "monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_id"
)

// Columns holds all SQL columns for statuspagemonitor fields.
var Columns = []string{
	FieldID,
	FieldStatusPageID,
	FieldMonitorID,
	FieldDisplayName,
	FieldWeight,
	FieldSendURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultSendURL holds the default value on creation for the "send_url" field.
	DefaultSendURL bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the StatusPageMonitor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatusPageID orders the results by the status_page_id field.
func ByStatusPageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusPageID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// BySendURL orders the results by the send_url field.
func BySendURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSendURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStatusPageField orders the results by status_page field.
func ByStatusPageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatusPageStep(), sql.OrderByField(field, opts...))
	}
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}
func newStatusPageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatusPageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StatusPageTable, StatusPageColumn),
	)
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
	)
}
