// Code generated by ent, DO NOT EDIT.

package statusmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Phoenix-Uptime/phoenix-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLTE(FieldID, id))
}

// StatusPageID applies equality check predicate on the "status_page_id" field. It's identical to StatusPageIDEQ.
func StatusPageID(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldStatusPageID, v))
}

// IncidentID applies equality check predicate on the "incident_id" field. It's identical to IncidentIDEQ.
func IncidentID(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldIncidentID, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldParentID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusPageIDEQ applies the EQ predicate on the "status_page_id" field.
func StatusPageIDEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldStatusPageID, v))
}

// StatusPageIDNEQ applies the NEQ predicate on the "status_page_id" field.
func StatusPageIDNEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldStatusPageID, v))
}

// StatusPageIDIn applies the In predicate on the "status_page_id" field.
func StatusPageIDIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldStatusPageID, vs...))
}

// StatusPageIDNotIn applies the NotIn predicate on the "status_page_id" field.
func StatusPageIDNotIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldStatusPageID, vs...))
}

// IncidentIDEQ applies the EQ predicate on the "incident_id" field.
func IncidentIDEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldIncidentID, v))
}

// IncidentIDNEQ applies the NEQ predicate on the "incident_id" field.
func IncidentIDNEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldIncidentID, v))
}

// IncidentIDIn applies the In predicate on the "incident_id" field.
func IncidentIDIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldIncidentID, vs...))
}

// IncidentIDNotIn applies the NotIn predicate on the "incident_id" field.
func IncidentIDNotIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldIncidentID, vs...))
}

// IncidentIDIsNil applies the IsNil predicate on the "incident_id" field.
func IncidentIDIsNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIsNull(FieldIncidentID))
}

// IncidentIDNotNil applies the NotNil predicate on the "incident_id" field.
func IncidentIDNotNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotNull(FieldIncidentID))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotNull(FieldParentID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldType, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StatusMessage {
	return predicate.StatusMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasStatusPage applies the HasEdge predicate on the "status_page" edge.
func HasStatusPage() predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StatusPageTable, StatusPageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatusPageWith applies the HasEdge predicate on the "status_page" edge with a given conditions (other predicates).
func HasStatusPageWith(preds ...predicate.StatusPage) predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := newStatusPageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIncident applies the HasEdge predicate on the "incident" edge.
func HasIncident() predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IncidentTable, IncidentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncidentWith applies the HasEdge predicate on the "incident" edge with a given conditions (other predicates).
func HasIncidentWith(preds ...predicate.Incident) predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := newIncidentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.StatusMessage) predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubMessages applies the HasEdge predicate on the "sub_messages" edge.
func HasSubMessages() predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubMessagesTable, SubMessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubMessagesWith applies the HasEdge predicate on the "sub_messages" edge with a given conditions (other predicates).
func HasSubMessagesWith(preds ...predicate.StatusMessage) predicate.StatusMessage {
	return predicate.StatusMessage(func(s *sql.Selector) {
		step := newSubMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StatusMessage) predicate.StatusMessage {
	return predicate.StatusMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StatusMessage) predicate.StatusMessage {
	return predicate.StatusMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StatusMessage) predicate.StatusMessage {
	return predicate.StatusMessage(sql.NotPredicates(p))
}
