// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[8]},
			},
			{
				Name:    "apikey_user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[8], APIKeysColumns[3]},
			},
		},
	}
	// IncidentsColumns holds the columns for the "incidents" table.
	IncidentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "acknowledged", "resolved"}, Default: "open"},
		{Name: "severity", Type: field.TypeEnum, Enums: []string{"info", "warning", "critical"}, Default: "warning"},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_pinned", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "monitor_id", Type: field.TypeInt},
		{Name: "status_page_id", Type: field.TypeInt, Nullable: true},
		{Name: "resolved_by_id", Type: field.TypeInt, Nullable: true},
	}
	// IncidentsTable holds the schema information for the "incidents" table.
	IncidentsTable = &schema.Table{
		Name:       "incidents",
		Columns:    IncidentsColumns,
		PrimaryKey: []*schema.Column{IncidentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "incidents_monitors_incidents",
				Columns:    []*schema.Column{IncidentsColumns[10]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "incidents_status_pages_incidents",
				Columns:    []*schema.Column{IncidentsColumns[11]},
				RefColumns: []*schema.Column{StatusPagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "incidents_users_resolved_incidents",
				Columns:    []*schema.Column{IncidentsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "incident_monitor_id",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[10]},
			},
			{
				Name:    "incident_monitor_id_status",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[10], IncidentsColumns[3]},
			},
			{
				Name:    "incident_status_page_id_status",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[11], IncidentsColumns[3]},
			},
			{
				Name:    "incident_status_started_at",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[3], IncidentsColumns[5]},
			},
			{
				Name:    "incident_started_at",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[5]},
			},
		},
	}
	// MaintenanceWindowsColumns holds the columns for the "maintenance_windows" table.
	MaintenanceWindowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "strategy", Type: field.TypeEnum, Enums: []string{"manual", "single", "recurring", "cron"}, Default: "single"},
		{Name: "start_at", Type: field.TypeTime, Nullable: true},
		{Name: "end_at", Type: field.TypeTime, Nullable: true},
		{Name: "cron", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Nullable: true},
		{Name: "duration_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MaintenanceWindowsTable holds the schema information for the "maintenance_windows" table.
	MaintenanceWindowsTable = &schema.Table{
		Name:       "maintenance_windows",
		Columns:    MaintenanceWindowsColumns,
		PrimaryKey: []*schema.Column{MaintenanceWindowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "maintenance_windows_users_maintenance_windows",
				Columns:    []*schema.Column{MaintenanceWindowsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "maintenancewindow_user_id",
				Unique:  false,
				Columns: []*schema.Column{MaintenanceWindowsColumns[12]},
			},
			{
				Name:    "maintenancewindow_user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{MaintenanceWindowsColumns[12], MaintenanceWindowsColumns[3]},
			},
			{
				Name:    "maintenancewindow_strategy_is_active",
				Unique:  false,
				Columns: []*schema.Column{MaintenanceWindowsColumns[4], MaintenanceWindowsColumns[3]},
			},
			{
				Name:    "maintenancewindow_start_at_end_at",
				Unique:  false,
				Columns: []*schema.Column{MaintenanceWindowsColumns[5], MaintenanceWindowsColumns[6]},
			},
		},
	}
	// MonitorsColumns holds the columns for the "monitors" table.
	MonitorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString},
		{Name: "interval", Type: field.TypeInt, Default: 60},
		{Name: "timeout", Type: field.TypeInt, Default: 10},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"up", "down", "pending", "maintenance", "paused", "unknown"}, Default: "unknown"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"http", "keyword", "json", "ping", "tcp", "smtp", "dns", "push", "grpc"}},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "method", Type: field.TypeString, Default: "GET"},
		{Name: "accepted_status_codes", Type: field.TypeJSON, Nullable: true},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "auth_username", Type: field.TypeString, Nullable: true},
		{Name: "auth_password", Type: field.TypeString, Nullable: true},
		{Name: "filters_contains", Type: field.TypeString, Nullable: true},
		{Name: "filters_not_contains", Type: field.TypeString, Nullable: true},
		{Name: "json_path", Type: field.TypeString, Nullable: true},
		{Name: "expected_value", Type: field.TypeString, Nullable: true},
		{Name: "ignore_tls_errors", Type: field.TypeBool, Default: false},
		{Name: "max_redirects", Type: field.TypeInt, Default: 10},
		{Name: "retry", Type: field.TypeInt, Default: 3},
		{Name: "retry_after", Type: field.TypeInt, Default: 30},
		{Name: "push_token", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MonitorsTable holds the schema information for the "monitors" table.
	MonitorsTable = &schema.Table{
		Name:       "monitors",
		Columns:    MonitorsColumns,
		PrimaryKey: []*schema.Column{MonitorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitors_users_monitors",
				Columns:    []*schema.Column{MonitorsColumns[27]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "monitor_user_id",
				Unique:  false,
				Columns: []*schema.Column{MonitorsColumns[27]},
			},
			{
				Name:    "monitor_user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{MonitorsColumns[27], MonitorsColumns[8]},
			},
			{
				Name:    "monitor_user_id_type",
				Unique:  false,
				Columns: []*schema.Column{MonitorsColumns[27], MonitorsColumns[7]},
			},
			{
				Name:    "monitor_status",
				Unique:  false,
				Columns: []*schema.Column{MonitorsColumns[6]},
			},
		},
	}
	// MonitorChecksColumns holds the columns for the "monitor_checks" table.
	MonitorChecksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"up", "down", "pending", "maintenance"}, Default: "pending"},
		{Name: "checked_at", Type: field.TypeTime},
		{Name: "response_time_ms", Type: field.TypeInt, Default: 0},
		{Name: "status_code", Type: field.TypeInt, Nullable: true},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "duration_seconds", Type: field.TypeInt, Default: 0},
		{Name: "important", Type: field.TypeBool, Default: false},
		{Name: "response", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "monitor_id", Type: field.TypeInt},
	}
	// MonitorChecksTable holds the schema information for the "monitor_checks" table.
	MonitorChecksTable = &schema.Table{
		Name:       "monitor_checks",
		Columns:    MonitorChecksColumns,
		PrimaryKey: []*schema.Column{MonitorChecksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitor_checks_monitors_checks",
				Columns:    []*schema.Column{MonitorChecksColumns[13]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "monitorcheck_monitor_id",
				Unique:  false,
				Columns: []*schema.Column{MonitorChecksColumns[13]},
			},
			{
				Name:    "monitorcheck_monitor_id_checked_at",
				Unique:  false,
				Columns: []*schema.Column{MonitorChecksColumns[13], MonitorChecksColumns[2]},
			},
			{
				Name:    "monitorcheck_monitor_id_important_checked_at",
				Unique:  false,
				Columns: []*schema.Column{MonitorChecksColumns[13], MonitorChecksColumns[9], MonitorChecksColumns[2]},
			},
			{
				Name:    "monitorcheck_checked_at",
				Unique:  false,
				Columns: []*schema.Column{MonitorChecksColumns[2]},
			},
		},
	}
	// MonitorStatsColumns holds the columns for the "monitor_stats" table.
	MonitorStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "period", Type: field.TypeEnum, Enums: []string{"hour", "day"}},
		{Name: "period_start", Type: field.TypeTime},
		{Name: "total_checks", Type: field.TypeInt, Default: 0},
		{Name: "up_checks", Type: field.TypeInt, Default: 0},
		{Name: "down_checks", Type: field.TypeInt, Default: 0},
		{Name: "maintenance_checks", Type: field.TypeInt, Default: 0},
		{Name: "uptime_percentage", Type: field.TypeFloat64, Default: 0},
		{Name: "avg_response_time_ms", Type: field.TypeInt, Default: 0},
		{Name: "min_response_time_ms", Type: field.TypeInt, Nullable: true},
		{Name: "max_response_time_ms", Type: field.TypeInt, Nullable: true},
		{Name: "downtime_seconds", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "monitor_id", Type: field.TypeInt},
	}
	// MonitorStatsTable holds the schema information for the "monitor_stats" table.
	MonitorStatsTable = &schema.Table{
		Name:       "monitor_stats",
		Columns:    MonitorStatsColumns,
		PrimaryKey: []*schema.Column{MonitorStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitor_stats_monitors_stats",
				Columns:    []*schema.Column{MonitorStatsColumns[14]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "monitorstat_monitor_id",
				Unique:  false,
				Columns: []*schema.Column{MonitorStatsColumns[14]},
			},
			{
				Name:    "monitorstat_period_start",
				Unique:  false,
				Columns: []*schema.Column{MonitorStatsColumns[2]},
			},
			{
				Name:    "monitorstat_monitor_id_period_period_start",
				Unique:  true,
				Columns: []*schema.Column{MonitorStatsColumns[14], MonitorStatsColumns[1], MonitorStatsColumns[2]},
			},
		},
	}
	// NotificationChannelsColumns holds the columns for the "notification_channels" table.
	NotificationChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"smtp", "telegram", "webhook", "ntfy"}},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "smtp_server", Type: field.TypeString, Nullable: true},
		{Name: "smtp_port", Type: field.TypeInt, Nullable: true},
		{Name: "smtp_from_address", Type: field.TypeString, Nullable: true},
		{Name: "smtp_username", Type: field.TypeString, Nullable: true},
		{Name: "smtp_password", Type: field.TypeString, Nullable: true},
		{Name: "smtp_use_tls", Type: field.TypeBool, Nullable: true},
		{Name: "telegram_bot_token", Type: field.TypeString, Nullable: true},
		{Name: "telegram_chat_id", Type: field.TypeString, Nullable: true},
		{Name: "webhook_url", Type: field.TypeString, Nullable: true},
		{Name: "webhook_method", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_server_url", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_topic", Type: field.TypeString, Nullable: true},
		{Name: "ntfy_token", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// NotificationChannelsTable holds the schema information for the "notification_channels" table.
	NotificationChannelsTable = &schema.Table{
		Name:       "notification_channels",
		Columns:    NotificationChannelsColumns,
		PrimaryKey: []*schema.Column{NotificationChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_channels_users_notification_channels",
				Columns:    []*schema.Column{NotificationChannelsColumns[20]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationchannel_user_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[20]},
			},
			{
				Name:    "notificationchannel_user_id_type",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[20], NotificationChannelsColumns[2]},
			},
			{
				Name:    "notificationchannel_user_id_is_default",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[20], NotificationChannelsColumns[4]},
			},
		},
	}
	// StatusMessagesColumns holds the columns for the "status_messages" table.
	StatusMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"issue", "investigating", "identified", "monitoring", "resolved", "maintenance"}},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "incident_id", Type: field.TypeInt, Nullable: true},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
		{Name: "status_page_id", Type: field.TypeInt},
	}
	// StatusMessagesTable holds the schema information for the "status_messages" table.
	StatusMessagesTable = &schema.Table{
		Name:       "status_messages",
		Columns:    StatusMessagesColumns,
		PrimaryKey: []*schema.Column{StatusMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "status_messages_incidents_messages",
				Columns:    []*schema.Column{StatusMessagesColumns[6]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "status_messages_status_messages_sub_messages",
				Columns:    []*schema.Column{StatusMessagesColumns[7]},
				RefColumns: []*schema.Column{StatusMessagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "status_messages_status_pages_messages",
				Columns:    []*schema.Column{StatusMessagesColumns[8]},
				RefColumns: []*schema.Column{StatusPagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "statusmessage_status_page_id",
				Unique:  false,
				Columns: []*schema.Column{StatusMessagesColumns[8]},
			},
			{
				Name:    "statusmessage_incident_id",
				Unique:  false,
				Columns: []*schema.Column{StatusMessagesColumns[6]},
			},
			{
				Name:    "statusmessage_parent_id",
				Unique:  false,
				Columns: []*schema.Column{StatusMessagesColumns[7]},
			},
		},
	}
	// StatusPagesColumns holds the columns for the "status_pages" table.
	StatusPagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_public", Type: field.TypeBool, Default: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "theme", Type: field.TypeString, Default: "default"},
		{Name: "custom_css", Type: field.TypeString, Nullable: true},
		{Name: "footer_text", Type: field.TypeString, Nullable: true},
		{Name: "show_tags", Type: field.TypeBool, Default: false},
		{Name: "show_charts", Type: field.TypeBool, Default: true},
		{Name: "show_uptime_percentage", Type: field.TypeBool, Default: true},
		{Name: "show_powered_by", Type: field.TypeBool, Default: true},
		{Name: "auto_refresh_interval", Type: field.TypeInt, Default: 300},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// StatusPagesTable holds the schema information for the "status_pages" table.
	StatusPagesTable = &schema.Table{
		Name:       "status_pages",
		Columns:    StatusPagesColumns,
		PrimaryKey: []*schema.Column{StatusPagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "status_pages_users_status_pages",
				Columns:    []*schema.Column{StatusPagesColumns[16]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "statuspage_user_id",
				Unique:  false,
				Columns: []*schema.Column{StatusPagesColumns[16]},
			},
			{
				Name:    "statuspage_user_id_slug",
				Unique:  true,
				Columns: []*schema.Column{StatusPagesColumns[16], StatusPagesColumns[1]},
			},
		},
	}
	// StatusPageMonitorsColumns holds the columns for the "status_page_monitors" table.
	StatusPageMonitorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "weight", Type: field.TypeInt, Default: 1000},
		{Name: "send_url", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "monitor_id", Type: field.TypeInt},
		{Name: "status_page_id", Type: field.TypeInt},
	}
	// StatusPageMonitorsTable holds the schema information for the "status_page_monitors" table.
	StatusPageMonitorsTable = &schema.Table{
		Name:       "status_page_monitors",
		Columns:    StatusPageMonitorsColumns,
		PrimaryKey: []*schema.Column{StatusPageMonitorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "status_page_monitors_monitors_status_page_monitors",
				Columns:    []*schema.Column{StatusPageMonitorsColumns[6]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "status_page_monitors_status_pages_status_page_monitors",
				Columns:    []*schema.Column{StatusPageMonitorsColumns[7]},
				RefColumns: []*schema.Column{StatusPagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "statuspagemonitor_status_page_id",
				Unique:  false,
				Columns: []*schema.Column{StatusPageMonitorsColumns[7]},
			},
			{
				Name:    "statuspagemonitor_monitor_id",
				Unique:  false,
				Columns: []*schema.Column{StatusPageMonitorsColumns[6]},
			},
			{
				Name:    "statuspagemonitor_status_page_id_monitor_id",
				Unique:  true,
				Columns: []*schema.Column{StatusPageMonitorsColumns[7], StatusPageMonitorsColumns[6]},
			},
			{
				Name:    "statuspagemonitor_status_page_id_weight",
				Unique:  false,
				Columns: []*schema.Column{StatusPageMonitorsColumns[7], StatusPageMonitorsColumns[2]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_users_tags",
				Columns:    []*schema.Column{TagsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tag_user_id",
				Unique:  false,
				Columns: []*schema.Column{TagsColumns[6]},
			},
			{
				Name:    "tag_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[6], TagsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "api_key", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_api_key",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// MonitorMaintenanceWindowsColumns holds the columns for the "monitor_maintenance_windows" table.
	MonitorMaintenanceWindowsColumns = []*schema.Column{
		{Name: "maintenance_window_id", Type: field.TypeInt},
		{Name: "monitor_id", Type: field.TypeInt},
	}
	// MonitorMaintenanceWindowsTable holds the schema information for the "monitor_maintenance_windows" table.
	MonitorMaintenanceWindowsTable = &schema.Table{
		Name:       "monitor_maintenance_windows",
		Columns:    MonitorMaintenanceWindowsColumns,
		PrimaryKey: []*schema.Column{MonitorMaintenanceWindowsColumns[0], MonitorMaintenanceWindowsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitor_maintenance_windows_maintenance_window_id",
				Columns:    []*schema.Column{MonitorMaintenanceWindowsColumns[0]},
				RefColumns: []*schema.Column{MaintenanceWindowsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "monitor_maintenance_windows_monitor_id",
				Columns:    []*schema.Column{MonitorMaintenanceWindowsColumns[1]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MonitorTagsColumns holds the columns for the "monitor_tags" table.
	MonitorTagsColumns = []*schema.Column{
		{Name: "monitor_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// MonitorTagsTable holds the schema information for the "monitor_tags" table.
	MonitorTagsTable = &schema.Table{
		Name:       "monitor_tags",
		Columns:    MonitorTagsColumns,
		PrimaryKey: []*schema.Column{MonitorTagsColumns[0], MonitorTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitor_tags_monitor_id",
				Columns:    []*schema.Column{MonitorTagsColumns[0]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "monitor_tags_tag_id",
				Columns:    []*schema.Column{MonitorTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MonitorNotificationChannelsColumns holds the columns for the "monitor_notification_channels" table.
	MonitorNotificationChannelsColumns = []*schema.Column{
		{Name: "monitor_id", Type: field.TypeInt},
		{Name: "notification_channel_id", Type: field.TypeInt},
	}
	// MonitorNotificationChannelsTable holds the schema information for the "monitor_notification_channels" table.
	MonitorNotificationChannelsTable = &schema.Table{
		Name:       "monitor_notification_channels",
		Columns:    MonitorNotificationChannelsColumns,
		PrimaryKey: []*schema.Column{MonitorNotificationChannelsColumns[0], MonitorNotificationChannelsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monitor_notification_channels_monitor_id",
				Columns:    []*schema.Column{MonitorNotificationChannelsColumns[0]},
				RefColumns: []*schema.Column{MonitorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "monitor_notification_channels_notification_channel_id",
				Columns:    []*schema.Column{MonitorNotificationChannelsColumns[1]},
				RefColumns: []*schema.Column{NotificationChannelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		IncidentsTable,
		MaintenanceWindowsTable,
		MonitorsTable,
		MonitorChecksTable,
		MonitorStatsTable,
		NotificationChannelsTable,
		StatusMessagesTable,
		StatusPagesTable,
		StatusPageMonitorsTable,
		TagsTable,
		UsersTable,
		MonitorMaintenanceWindowsTable,
		MonitorTagsTable,
		MonitorNotificationChannelsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = UsersTable
	IncidentsTable.ForeignKeys[0].RefTable = MonitorsTable
	IncidentsTable.ForeignKeys[1].RefTable = StatusPagesTable
	IncidentsTable.ForeignKeys[2].RefTable = UsersTable
	MaintenanceWindowsTable.ForeignKeys[0].RefTable = UsersTable
	MonitorsTable.ForeignKeys[0].RefTable = UsersTable
	MonitorChecksTable.ForeignKeys[0].RefTable = MonitorsTable
	MonitorStatsTable.ForeignKeys[0].RefTable = MonitorsTable
	NotificationChannelsTable.ForeignKeys[0].RefTable = UsersTable
	StatusMessagesTable.ForeignKeys[0].RefTable = IncidentsTable
	StatusMessagesTable.ForeignKeys[1].RefTable = StatusMessagesTable
	StatusMessagesTable.ForeignKeys[2].RefTable = StatusPagesTable
	StatusPagesTable.ForeignKeys[0].RefTable = UsersTable
	StatusPageMonitorsTable.ForeignKeys[0].RefTable = MonitorsTable
	StatusPageMonitorsTable.ForeignKeys[1].RefTable = StatusPagesTable
	TagsTable.ForeignKeys[0].RefTable = UsersTable
	MonitorMaintenanceWindowsTable.ForeignKeys[0].RefTable = MaintenanceWindowsTable
	MonitorMaintenanceWindowsTable.ForeignKeys[1].RefTable = MonitorsTable
	MonitorTagsTable.ForeignKeys[0].RefTable = MonitorsTable
	MonitorTagsTable.ForeignKeys[1].RefTable = TagsTable
	MonitorNotificationChannelsTable.ForeignKeys[0].RefTable = MonitorsTable
	MonitorNotificationChannelsTable.ForeignKeys[1].RefTable = NotificationChannelsTable
}
