// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/alertdelivery"
	"github.com/Phoenix-Uptime/phoenix-go/ent/alertrule"
	"github.com/Phoenix-Uptime/phoenix-go/ent/incident"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitor"
	"github.com/Phoenix-Uptime/phoenix-go/ent/notificationchannel"
)

// AlertDeliveryCreate is the builder for creating a AlertDelivery entity.
type AlertDeliveryCreate struct {
	config
	mutation *AlertDeliveryMutation
	hooks    []Hook
}

// SetAlertRuleID sets the "alert_rule_id" field.
func (_c *AlertDeliveryCreate) SetAlertRuleID(v int) *AlertDeliveryCreate {
	_c.mutation.SetAlertRuleID(v)
	return _c
}

// SetNotificationChannelID sets the "notification_channel_id" field.
func (_c *AlertDeliveryCreate) SetNotificationChannelID(v int) *AlertDeliveryCreate {
	_c.mutation.SetNotificationChannelID(v)
	return _c
}

// SetMonitorID sets the "monitor_id" field.
func (_c *AlertDeliveryCreate) SetMonitorID(v int) *AlertDeliveryCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableMonitorID(v *int) *AlertDeliveryCreate {
	if v != nil {
		_c.SetMonitorID(*v)
	}
	return _c
}

// SetIncidentID sets the "incident_id" field.
func (_c *AlertDeliveryCreate) SetIncidentID(v int) *AlertDeliveryCreate {
	_c.mutation.SetIncidentID(v)
	return _c
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableIncidentID(v *int) *AlertDeliveryCreate {
	if v != nil {
		_c.SetIncidentID(*v)
	}
	return _c
}

// SetEvent sets the "event" field.
func (_c *AlertDeliveryCreate) SetEvent(v alertdelivery.Event) *AlertDeliveryCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AlertDeliveryCreate) SetStatus(v alertdelivery.Status) *AlertDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableStatus(v *alertdelivery.Status) *AlertDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *AlertDeliveryCreate) SetError(v string) *AlertDeliveryCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableError(v *string) *AlertDeliveryCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *AlertDeliveryCreate) SetRetryCount(v int) *AlertDeliveryCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableRetryCount(v *int) *AlertDeliveryCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *AlertDeliveryCreate) SetSentAt(v time.Time) *AlertDeliveryCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableSentAt(v *time.Time) *AlertDeliveryCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AlertDeliveryCreate) SetCreatedAt(v time.Time) *AlertDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableCreatedAt(v *time.Time) *AlertDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AlertDeliveryCreate) SetUpdatedAt(v time.Time) *AlertDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AlertDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *AlertDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAlertRule sets the "alert_rule" edge to the AlertRule entity.
func (_c *AlertDeliveryCreate) SetAlertRule(v *AlertRule) *AlertDeliveryCreate {
	return _c.SetAlertRuleID(v.ID)
}

// SetNotificationChannel sets the "notification_channel" edge to the NotificationChannel entity.
func (_c *AlertDeliveryCreate) SetNotificationChannel(v *NotificationChannel) *AlertDeliveryCreate {
	return _c.SetNotificationChannelID(v.ID)
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (_c *AlertDeliveryCreate) SetMonitor(v *Monitor) *AlertDeliveryCreate {
	return _c.SetMonitorID(v.ID)
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_c *AlertDeliveryCreate) SetIncident(v *Incident) *AlertDeliveryCreate {
	return _c.SetIncidentID(v.ID)
}

// Mutation returns the AlertDeliveryMutation object of the builder.
func (_c *AlertDeliveryCreate) Mutation() *AlertDeliveryMutation {
	return _c.mutation
}

// Save creates the AlertDelivery in the database.
func (_c *AlertDeliveryCreate) Save(ctx context.Context) (*AlertDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertDeliveryCreate) SaveX(ctx context.Context) *AlertDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := alertdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := alertdelivery.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := alertdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := alertdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertDeliveryCreate) check() error {
	if _, ok := _c.mutation.AlertRuleID(); !ok {
		return &ValidationError{Name: "alert_rule_id", err: errors.New(`ent: missing required field "AlertDelivery.alert_rule_id"`)}
	}
	if _, ok := _c.mutation.NotificationChannelID(); !ok {
		return &ValidationError{Name: "notification_channel_id", err: errors.New(`ent: missing required field "AlertDelivery.notification_channel_id"`)}
	}
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "AlertDelivery.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := alertdelivery.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "AlertDelivery.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlertDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := alertdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "AlertDelivery.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AlertDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AlertDelivery.updated_at"`)}
	}
	if len(_c.mutation.AlertRuleIDs()) == 0 {
		return &ValidationError{Name: "alert_rule", err: errors.New(`ent: missing required edge "AlertDelivery.alert_rule"`)}
	}
	if len(_c.mutation.NotificationChannelIDs()) == 0 {
		return &ValidationError{Name: "notification_channel", err: errors.New(`ent: missing required edge "AlertDelivery.notification_channel"`)}
	}
	return nil
}

func (_c *AlertDeliveryCreate) sqlSave(ctx context.Context) (*AlertDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertDeliveryCreate) createSpec() (*AlertDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertdelivery.Table, sqlgraph.NewFieldSpec(alertdelivery.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(alertdelivery.FieldEvent, field.TypeEnum, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(alertdelivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(alertdelivery.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(alertdelivery.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(alertdelivery.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(alertdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(alertdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AlertRuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertdelivery.AlertRuleTable,
			Columns: []string{alertdelivery.AlertRuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AlertRuleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertdelivery.NotificationChannelTable,
			Columns: []string{alertdelivery.NotificationChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertdelivery.MonitorTable,
			Columns: []string{alertdelivery.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MonitorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertdelivery.IncidentTable,
			Columns: []string{alertdelivery.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IncidentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlertDeliveryCreateBulk is the builder for creating many AlertDelivery entities in bulk.
type AlertDeliveryCreateBulk struct {
	config
	err      error
	builders []*AlertDeliveryCreate
}

// Save creates the AlertDelivery entities in the database.
func (_c *AlertDeliveryCreateBulk) Save(ctx context.Context) ([]*AlertDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertDeliveryCreateBulk) SaveX(ctx context.Context) []*AlertDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
