// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Phoenix-Uptime/phoenix-go/ent/alertrule"
	"github.com/Phoenix-Uptime/phoenix-go/ent/user"
)

// AlertRule is the model entity for the AlertRule schema.
type AlertRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Event holds the value of the "event" field.
	Event alertrule.Event `json:"event,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope alertrule.Scope `json:"scope,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// ResendIntervalSeconds holds the value of the "resend_interval_seconds" field.
	ResendIntervalSeconds *int `json:"resend_interval_seconds,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertRuleQuery when eager-loading is set.
	Edges        AlertRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertRuleEdges holds the relations/edges for other nodes in the graph.
type AlertRuleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Monitors holds the value of the monitors edge.
	Monitors []*Monitor `json:"monitors,omitempty"`
	// NotificationChannels holds the value of the notification_channels edge.
	NotificationChannels []*NotificationChannel `json:"notification_channels,omitempty"`
	// Deliveries holds the value of the deliveries edge.
	Deliveries []*AlertDelivery `json:"deliveries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertRuleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e AlertRuleEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// MonitorsOrErr returns the Monitors value or an error if the edge
// was not loaded in eager-loading.
func (e AlertRuleEdges) MonitorsOrErr() ([]*Monitor, error) {
	if e.loadedTypes[2] {
		return e.Monitors, nil
	}
	return nil, &NotLoadedError{edge: "monitors"}
}

// NotificationChannelsOrErr returns the NotificationChannels value or an error if the edge
// was not loaded in eager-loading.
func (e AlertRuleEdges) NotificationChannelsOrErr() ([]*NotificationChannel, error) {
	if e.loadedTypes[3] {
		return e.NotificationChannels, nil
	}
	return nil, &NotLoadedError{edge: "notification_channels"}
}

// DeliveriesOrErr returns the Deliveries value or an error if the edge
// was not loaded in eager-loading.
func (e AlertRuleEdges) DeliveriesOrErr() ([]*AlertDelivery, error) {
	if e.loadedTypes[4] {
		return e.Deliveries, nil
	}
	return nil, &NotLoadedError{edge: "deliveries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertrule.FieldIsActive:
			values[i] = new(sql.NullBool)
		case alertrule.FieldID, alertrule.FieldUserID, alertrule.FieldResendIntervalSeconds:
			values[i] = new(sql.NullInt64)
		case alertrule.FieldName, alertrule.FieldDescription, alertrule.FieldEvent, alertrule.FieldScope:
			values[i] = new(sql.NullString)
		case alertrule.FieldCreatedAt, alertrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertRule fields.
func (_m *AlertRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case alertrule.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case alertrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case alertrule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case alertrule.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = alertrule.Event(value.String)
			}
		case alertrule.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = alertrule.Scope(value.String)
			}
		case alertrule.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case alertrule.FieldResendIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resend_interval_seconds", values[i])
			} else if value.Valid {
				_m.ResendIntervalSeconds = new(int)
				*_m.ResendIntervalSeconds = int(value.Int64)
			}
		case alertrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case alertrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertRule.
// This includes values selected through modifiers, order, etc.
func (_m *AlertRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the AlertRule entity.
func (_m *AlertRule) QueryUser() *UserQuery {
	return NewAlertRuleClient(_m.config).QueryUser(_m)
}

// QueryTags queries the "tags" edge of the AlertRule entity.
func (_m *AlertRule) QueryTags() *TagQuery {
	return NewAlertRuleClient(_m.config).QueryTags(_m)
}

// QueryMonitors queries the "monitors" edge of the AlertRule entity.
func (_m *AlertRule) QueryMonitors() *MonitorQuery {
	return NewAlertRuleClient(_m.config).QueryMonitors(_m)
}

// QueryNotificationChannels queries the "notification_channels" edge of the AlertRule entity.
func (_m *AlertRule) QueryNotificationChannels() *NotificationChannelQuery {
	return NewAlertRuleClient(_m.config).QueryNotificationChannels(_m)
}

// QueryDeliveries queries the "deliveries" edge of the AlertRule entity.
func (_m *AlertRule) QueryDeliveries() *AlertDeliveryQuery {
	return NewAlertRuleClient(_m.config).QueryDeliveries(_m)
}

// Update returns a builder for updating this AlertRule.
// Note that you need to call AlertRule.Unwrap() before calling this method if this AlertRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertRule) Update() *AlertRuleUpdateOne {
	return NewAlertRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertRule) Unwrap() *AlertRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertRule) String() string {
	var builder strings.Builder
	builder.WriteString("AlertRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(fmt.Sprintf("%v", _m.Event))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scope))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.ResendIntervalSeconds; v != nil {
		builder.WriteString("resend_interval_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlertRules is a parsable slice of AlertRule.
type AlertRules []*AlertRule
