// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Phoenix-Uptime/phoenix-go/ent/incident"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitor"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statuspage"
	"github.com/Phoenix-Uptime/phoenix-go/ent/user"
)

// Incident is the model entity for the Incident schema.
type Incident struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int `json:"monitor_id,omitempty"`
	// StatusPageID holds the value of the "status_page_id" field.
	StatusPageID *int `json:"status_page_id,omitempty"`
	// ResolvedByID holds the value of the "resolved_by_id" field.
	ResolvedByID *int `json:"resolved_by_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content *string `json:"content,omitempty"`
	// Status holds the value of the "status" field.
	Status incident.Status `json:"status,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity incident.Severity `json:"severity,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// IsPinned holds the value of the "is_pinned" field.
	IsPinned bool `json:"is_pinned,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IncidentQuery when eager-loading is set.
	Edges        IncidentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IncidentEdges holds the relations/edges for other nodes in the graph.
type IncidentEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *Monitor `json:"monitor,omitempty"`
	// StatusPage holds the value of the status_page edge.
	StatusPage *StatusPage `json:"status_page,omitempty"`
	// ResolvedBy holds the value of the resolved_by edge.
	ResolvedBy *User `json:"resolved_by,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*StatusMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentEdges) MonitorOrErr() (*Monitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: monitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// StatusPageOrErr returns the StatusPage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentEdges) StatusPageOrErr() (*StatusPage, error) {
	if e.StatusPage != nil {
		return e.StatusPage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: statuspage.Label}
	}
	return nil, &NotLoadedError{edge: "status_page"}
}

// ResolvedByOrErr returns the ResolvedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentEdges) ResolvedByOrErr() (*User, error) {
	if e.ResolvedBy != nil {
		return e.ResolvedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "resolved_by"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e IncidentEdges) MessagesOrErr() ([]*StatusMessage, error) {
	if e.loadedTypes[3] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Incident) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case incident.FieldIsPinned:
			values[i] = new(sql.NullBool)
		case incident.FieldID, incident.FieldMonitorID, incident.FieldStatusPageID, incident.FieldResolvedByID:
			values[i] = new(sql.NullInt64)
		case incident.FieldTitle, incident.FieldContent, incident.FieldStatus, incident.FieldSeverity:
			values[i] = new(sql.NullString)
		case incident.FieldCreatedAt, incident.FieldUpdatedAt, incident.FieldStartedAt, incident.FieldEndedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Incident fields.
func (_m *Incident) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case incident.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case incident.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case incident.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case incident.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = int(value.Int64)
			}
		case incident.FieldStatusPageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_page_id", values[i])
			} else if value.Valid {
				_m.StatusPageID = new(int)
				*_m.StatusPageID = int(value.Int64)
			}
		case incident.FieldResolvedByID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by_id", values[i])
			} else if value.Valid {
				_m.ResolvedByID = new(int)
				*_m.ResolvedByID = int(value.Int64)
			}
		case incident.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case incident.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = new(string)
				*_m.Content = value.String
			}
		case incident.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = incident.Status(value.String)
			}
		case incident.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = incident.Severity(value.String)
			}
		case incident.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case incident.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case incident.FieldIsPinned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_pinned", values[i])
			} else if value.Valid {
				_m.IsPinned = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Incident.
// This includes values selected through modifiers, order, etc.
func (_m *Incident) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the Incident entity.
func (_m *Incident) QueryMonitor() *MonitorQuery {
	return NewIncidentClient(_m.config).QueryMonitor(_m)
}

// QueryStatusPage queries the "status_page" edge of the Incident entity.
func (_m *Incident) QueryStatusPage() *StatusPageQuery {
	return NewIncidentClient(_m.config).QueryStatusPage(_m)
}

// QueryResolvedBy queries the "resolved_by" edge of the Incident entity.
func (_m *Incident) QueryResolvedBy() *UserQuery {
	return NewIncidentClient(_m.config).QueryResolvedBy(_m)
}

// QueryMessages queries the "messages" edge of the Incident entity.
func (_m *Incident) QueryMessages() *StatusMessageQuery {
	return NewIncidentClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this Incident.
// Note that you need to call Incident.Unwrap() before calling this method if this Incident
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Incident) Update() *IncidentUpdateOne {
	return NewIncidentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Incident entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Incident) Unwrap() *Incident {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Incident is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Incident) String() string {
	var builder strings.Builder
	builder.WriteString("Incident(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	if v := _m.StatusPageID; v != nil {
		builder.WriteString("status_page_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedByID; v != nil {
		builder.WriteString("resolved_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Content; v != nil {
		builder.WriteString("content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Severity))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_pinned=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPinned))
	builder.WriteByte(')')
	return builder.String()
}

// Incidents is a parsable slice of Incident.
type Incidents []*Incident
