// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/maintenancewindow"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitor"
	"github.com/Phoenix-Uptime/phoenix-go/ent/predicate"
	"github.com/Phoenix-Uptime/phoenix-go/ent/user"
)

// MaintenanceWindowUpdate is the builder for updating MaintenanceWindow entities.
type MaintenanceWindowUpdate struct {
	config
	hooks    []Hook
	mutation *MaintenanceWindowMutation
}

// Where appends a list predicates to the MaintenanceWindowUpdate builder.
func (_u *MaintenanceWindowUpdate) Where(ps ...predicate.MaintenanceWindow) *MaintenanceWindowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MaintenanceWindowUpdate) SetUpdatedAt(v time.Time) *MaintenanceWindowUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MaintenanceWindowUpdate) SetDeletedAt(v time.Time) *MaintenanceWindowUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableDeletedAt(v *time.Time) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MaintenanceWindowUpdate) ClearDeletedAt() *MaintenanceWindowUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MaintenanceWindowUpdate) SetUserID(v int) *MaintenanceWindowUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableUserID(v *int) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MaintenanceWindowUpdate) SetTitle(v string) *MaintenanceWindowUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableTitle(v *string) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MaintenanceWindowUpdate) SetDescription(v string) *MaintenanceWindowUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableDescription(v *string) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MaintenanceWindowUpdate) ClearDescription() *MaintenanceWindowUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MaintenanceWindowUpdate) SetIsActive(v bool) *MaintenanceWindowUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableIsActive(v *bool) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetStrategy sets the "strategy" field.
func (_u *MaintenanceWindowUpdate) SetStrategy(v maintenancewindow.Strategy) *MaintenanceWindowUpdate {
	_u.mutation.SetStrategy(v)
	return _u
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableStrategy(v *maintenancewindow.Strategy) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetStrategy(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *MaintenanceWindowUpdate) SetStartAt(v time.Time) *MaintenanceWindowUpdate {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableStartAt(v *time.Time) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *MaintenanceWindowUpdate) ClearStartAt() *MaintenanceWindowUpdate {
	_u.mutation.ClearStartAt()
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *MaintenanceWindowUpdate) SetEndAt(v time.Time) *MaintenanceWindowUpdate {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableEndAt(v *time.Time) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *MaintenanceWindowUpdate) ClearEndAt() *MaintenanceWindowUpdate {
	_u.mutation.ClearEndAt()
	return _u
}

// SetCron sets the "cron" field.
func (_u *MaintenanceWindowUpdate) SetCron(v string) *MaintenanceWindowUpdate {
	_u.mutation.SetCron(v)
	return _u
}

// SetNillableCron sets the "cron" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableCron(v *string) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetCron(*v)
	}
	return _u
}

// ClearCron clears the value of the "cron" field.
func (_u *MaintenanceWindowUpdate) ClearCron() *MaintenanceWindowUpdate {
	_u.mutation.ClearCron()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *MaintenanceWindowUpdate) SetTimezone(v string) *MaintenanceWindowUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableTimezone(v *string) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *MaintenanceWindowUpdate) ClearTimezone() *MaintenanceWindowUpdate {
	_u.mutation.ClearTimezone()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *MaintenanceWindowUpdate) SetDurationSeconds(v int) *MaintenanceWindowUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *MaintenanceWindowUpdate) SetNillableDurationSeconds(v *int) *MaintenanceWindowUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *MaintenanceWindowUpdate) AddDurationSeconds(v int) *MaintenanceWindowUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *MaintenanceWindowUpdate) ClearDurationSeconds() *MaintenanceWindowUpdate {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MaintenanceWindowUpdate) SetUser(v *User) *MaintenanceWindowUpdate {
	return _u.SetUserID(v.ID)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (_u *MaintenanceWindowUpdate) AddMonitorIDs(ids ...int) *MaintenanceWindowUpdate {
	_u.mutation.AddMonitorIDs(ids...)
	return _u
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (_u *MaintenanceWindowUpdate) AddMonitors(v ...*Monitor) *MaintenanceWindowUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonitorIDs(ids...)
}

// Mutation returns the MaintenanceWindowMutation object of the builder.
func (_u *MaintenanceWindowUpdate) Mutation() *MaintenanceWindowMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MaintenanceWindowUpdate) ClearUser() *MaintenanceWindowUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (_u *MaintenanceWindowUpdate) ClearMonitors() *MaintenanceWindowUpdate {
	_u.mutation.ClearMonitors()
	return _u
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (_u *MaintenanceWindowUpdate) RemoveMonitorIDs(ids ...int) *MaintenanceWindowUpdate {
	_u.mutation.RemoveMonitorIDs(ids...)
	return _u
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (_u *MaintenanceWindowUpdate) RemoveMonitors(v ...*Monitor) *MaintenanceWindowUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonitorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MaintenanceWindowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MaintenanceWindowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MaintenanceWindowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MaintenanceWindowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MaintenanceWindowUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := maintenancewindow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MaintenanceWindowUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := maintenancewindow.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MaintenanceWindow.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Strategy(); ok {
		if err := maintenancewindow.StrategyValidator(v); err != nil {
			return &ValidationError{Name: "strategy", err: fmt.Errorf(`ent: validator failed for field "MaintenanceWindow.strategy": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MaintenanceWindow.user"`)
	}
	return nil
}

func (_u *MaintenanceWindowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maintenancewindow.Table, maintenancewindow.Columns, sqlgraph.NewFieldSpec(maintenancewindow.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(maintenancewindow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(maintenancewindow.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(maintenancewindow.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(maintenancewindow.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(maintenancewindow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(maintenancewindow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(maintenancewindow.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Strategy(); ok {
		_spec.SetField(maintenancewindow.FieldStrategy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(maintenancewindow.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(maintenancewindow.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(maintenancewindow.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(maintenancewindow.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Cron(); ok {
		_spec.SetField(maintenancewindow.FieldCron, field.TypeString, value)
	}
	if _u.mutation.CronCleared() {
		_spec.ClearField(maintenancewindow.FieldCron, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(maintenancewindow.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(maintenancewindow.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(maintenancewindow.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(maintenancewindow.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(maintenancewindow.FieldDurationSeconds, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   maintenancewindow.UserTable,
			Columns: []string{maintenancewindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   maintenancewindow.UserTable,
			Columns: []string{maintenancewindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !_u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maintenancewindow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MaintenanceWindowUpdateOne is the builder for updating a single MaintenanceWindow entity.
type MaintenanceWindowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MaintenanceWindowMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MaintenanceWindowUpdateOne) SetUpdatedAt(v time.Time) *MaintenanceWindowUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MaintenanceWindowUpdateOne) SetDeletedAt(v time.Time) *MaintenanceWindowUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableDeletedAt(v *time.Time) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MaintenanceWindowUpdateOne) ClearDeletedAt() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MaintenanceWindowUpdateOne) SetUserID(v int) *MaintenanceWindowUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableUserID(v *int) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MaintenanceWindowUpdateOne) SetTitle(v string) *MaintenanceWindowUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableTitle(v *string) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MaintenanceWindowUpdateOne) SetDescription(v string) *MaintenanceWindowUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableDescription(v *string) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MaintenanceWindowUpdateOne) ClearDescription() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *MaintenanceWindowUpdateOne) SetIsActive(v bool) *MaintenanceWindowUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableIsActive(v *bool) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetStrategy sets the "strategy" field.
func (_u *MaintenanceWindowUpdateOne) SetStrategy(v maintenancewindow.Strategy) *MaintenanceWindowUpdateOne {
	_u.mutation.SetStrategy(v)
	return _u
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableStrategy(v *maintenancewindow.Strategy) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetStrategy(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *MaintenanceWindowUpdateOne) SetStartAt(v time.Time) *MaintenanceWindowUpdateOne {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableStartAt(v *time.Time) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *MaintenanceWindowUpdateOne) ClearStartAt() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearStartAt()
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *MaintenanceWindowUpdateOne) SetEndAt(v time.Time) *MaintenanceWindowUpdateOne {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableEndAt(v *time.Time) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *MaintenanceWindowUpdateOne) ClearEndAt() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearEndAt()
	return _u
}

// SetCron sets the "cron" field.
func (_u *MaintenanceWindowUpdateOne) SetCron(v string) *MaintenanceWindowUpdateOne {
	_u.mutation.SetCron(v)
	return _u
}

// SetNillableCron sets the "cron" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableCron(v *string) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetCron(*v)
	}
	return _u
}

// ClearCron clears the value of the "cron" field.
func (_u *MaintenanceWindowUpdateOne) ClearCron() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearCron()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *MaintenanceWindowUpdateOne) SetTimezone(v string) *MaintenanceWindowUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableTimezone(v *string) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// ClearTimezone clears the value of the "timezone" field.
func (_u *MaintenanceWindowUpdateOne) ClearTimezone() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearTimezone()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *MaintenanceWindowUpdateOne) SetDurationSeconds(v int) *MaintenanceWindowUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *MaintenanceWindowUpdateOne) SetNillableDurationSeconds(v *int) *MaintenanceWindowUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *MaintenanceWindowUpdateOne) AddDurationSeconds(v int) *MaintenanceWindowUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *MaintenanceWindowUpdateOne) ClearDurationSeconds() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MaintenanceWindowUpdateOne) SetUser(v *User) *MaintenanceWindowUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (_u *MaintenanceWindowUpdateOne) AddMonitorIDs(ids ...int) *MaintenanceWindowUpdateOne {
	_u.mutation.AddMonitorIDs(ids...)
	return _u
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (_u *MaintenanceWindowUpdateOne) AddMonitors(v ...*Monitor) *MaintenanceWindowUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonitorIDs(ids...)
}

// Mutation returns the MaintenanceWindowMutation object of the builder.
func (_u *MaintenanceWindowUpdateOne) Mutation() *MaintenanceWindowMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MaintenanceWindowUpdateOne) ClearUser() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (_u *MaintenanceWindowUpdateOne) ClearMonitors() *MaintenanceWindowUpdateOne {
	_u.mutation.ClearMonitors()
	return _u
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (_u *MaintenanceWindowUpdateOne) RemoveMonitorIDs(ids ...int) *MaintenanceWindowUpdateOne {
	_u.mutation.RemoveMonitorIDs(ids...)
	return _u
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (_u *MaintenanceWindowUpdateOne) RemoveMonitors(v ...*Monitor) *MaintenanceWindowUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonitorIDs(ids...)
}

// Where appends a list predicates to the MaintenanceWindowUpdate builder.
func (_u *MaintenanceWindowUpdateOne) Where(ps ...predicate.MaintenanceWindow) *MaintenanceWindowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MaintenanceWindowUpdateOne) Select(field string, fields ...string) *MaintenanceWindowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MaintenanceWindow entity.
func (_u *MaintenanceWindowUpdateOne) Save(ctx context.Context) (*MaintenanceWindow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MaintenanceWindowUpdateOne) SaveX(ctx context.Context) *MaintenanceWindow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MaintenanceWindowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MaintenanceWindowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MaintenanceWindowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := maintenancewindow.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MaintenanceWindowUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := maintenancewindow.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MaintenanceWindow.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Strategy(); ok {
		if err := maintenancewindow.StrategyValidator(v); err != nil {
			return &ValidationError{Name: "strategy", err: fmt.Errorf(`ent: validator failed for field "MaintenanceWindow.strategy": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MaintenanceWindow.user"`)
	}
	return nil
}

func (_u *MaintenanceWindowUpdateOne) sqlSave(ctx context.Context) (_node *MaintenanceWindow, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maintenancewindow.Table, maintenancewindow.Columns, sqlgraph.NewFieldSpec(maintenancewindow.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MaintenanceWindow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, maintenancewindow.FieldID)
		for _, f := range fields {
			if !maintenancewindow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != maintenancewindow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(maintenancewindow.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(maintenancewindow.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(maintenancewindow.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(maintenancewindow.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(maintenancewindow.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(maintenancewindow.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(maintenancewindow.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Strategy(); ok {
		_spec.SetField(maintenancewindow.FieldStrategy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(maintenancewindow.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(maintenancewindow.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(maintenancewindow.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(maintenancewindow.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Cron(); ok {
		_spec.SetField(maintenancewindow.FieldCron, field.TypeString, value)
	}
	if _u.mutation.CronCleared() {
		_spec.ClearField(maintenancewindow.FieldCron, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(maintenancewindow.FieldTimezone, field.TypeString, value)
	}
	if _u.mutation.TimezoneCleared() {
		_spec.ClearField(maintenancewindow.FieldTimezone, field.TypeString)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(maintenancewindow.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(maintenancewindow.FieldDurationSeconds, field.TypeInt, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(maintenancewindow.FieldDurationSeconds, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   maintenancewindow.UserTable,
			Columns: []string{maintenancewindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   maintenancewindow.UserTable,
			Columns: []string{maintenancewindow.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !_u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   maintenancewindow.MonitorsTable,
			Columns: maintenancewindow.MonitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MaintenanceWindow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maintenancewindow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
