// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitor"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitorcheck"
)

// MonitorCheck is the model entity for the MonitorCheck schema.
type MonitorCheck struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int `json:"monitor_id,omitempty"`
	// Status holds the value of the "status" field.
	Status monitorcheck.Status `json:"status,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// ResponseTimeMs holds the value of the "response_time_ms" field.
	ResponseTimeMs int `json:"response_time_ms,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// Message holds the value of the "message" field.
	Message *string `json:"message,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds int `json:"duration_seconds,omitempty"`
	// Important holds the value of the "important" field.
	Important bool `json:"important,omitempty"`
	// Response holds the value of the "response" field.
	Response *string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MonitorCheckQuery when eager-loading is set.
	Edges        MonitorCheckEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MonitorCheckEdges holds the relations/edges for other nodes in the graph.
type MonitorCheckEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *Monitor `json:"monitor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) MonitorOrErr() (*Monitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: monitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorCheck) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorcheck.FieldImportant:
			values[i] = new(sql.NullBool)
		case monitorcheck.FieldID, monitorcheck.FieldMonitorID, monitorcheck.FieldResponseTimeMs, monitorcheck.FieldStatusCode, monitorcheck.FieldRetryCount, monitorcheck.FieldDurationSeconds:
			values[i] = new(sql.NullInt64)
		case monitorcheck.FieldStatus, monitorcheck.FieldMessage, monitorcheck.FieldError, monitorcheck.FieldResponse:
			values[i] = new(sql.NullString)
		case monitorcheck.FieldCreatedAt, monitorcheck.FieldUpdatedAt, monitorcheck.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorCheck fields.
func (_m *MonitorCheck) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorcheck.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case monitorcheck.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case monitorcheck.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case monitorcheck.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = int(value.Int64)
			}
		case monitorcheck.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = monitorcheck.Status(value.String)
			}
		case monitorcheck.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		case monitorcheck.FieldResponseTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_time_ms", values[i])
			} else if value.Valid {
				_m.ResponseTimeMs = int(value.Int64)
			}
		case monitorcheck.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case monitorcheck.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case monitorcheck.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case monitorcheck.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case monitorcheck.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = int(value.Int64)
			}
		case monitorcheck.FieldImportant:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field important", values[i])
			} else if value.Valid {
				_m.Important = value.Bool
			}
		case monitorcheck.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				_m.Response = new(string)
				*_m.Response = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorCheck.
// This includes values selected through modifiers, order, etc.
func (_m *MonitorCheck) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the MonitorCheck entity.
func (_m *MonitorCheck) QueryMonitor() *MonitorQuery {
	return NewMonitorCheckClient(_m.config).QueryMonitor(_m)
}

// Update returns a builder for updating this MonitorCheck.
// Note that you need to call MonitorCheck.Unwrap() before calling this method if this MonitorCheck
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MonitorCheck) Update() *MonitorCheckUpdateOne {
	return NewMonitorCheckClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MonitorCheck entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MonitorCheck) Unwrap() *MonitorCheck {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorCheck is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MonitorCheck) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorCheck(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("response_time_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseTimeMs))
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("important=")
	builder.WriteString(fmt.Sprintf("%v", _m.Important))
	builder.WriteString(", ")
	builder.WriteString("response=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// MonitorChecks is a parsable slice of MonitorCheck.
type MonitorChecks []*MonitorCheck
