// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/predicate"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statusmessage"
)

// StatusMessageDelete is the builder for deleting a StatusMessage entity.
type StatusMessageDelete struct {
	config
	hooks    []Hook
	mutation *StatusMessageMutation
}

// Where appends a list predicates to the StatusMessageDelete builder.
func (_d *StatusMessageDelete) Where(ps ...predicate.StatusMessage) *StatusMessageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StatusMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StatusMessageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StatusMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(statusmessage.Table, sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StatusMessageDeleteOne is the builder for deleting a single StatusMessage entity.
type StatusMessageDeleteOne struct {
	_d *StatusMessageDelete
}

// Where appends a list predicates to the StatusMessageDelete builder.
func (_d *StatusMessageDeleteOne) Where(ps ...predicate.StatusMessage) *StatusMessageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StatusMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{statusmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StatusMessageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
