// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statusmessage"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statuspage"
	"github.com/Phoenix-Uptime/phoenix-go/ent/tag"
)

// StatusPageCreate is the builder for creating a StatusPage entity.
type StatusPageCreate struct {
	config
	mutation *StatusPageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *StatusPageCreate) SetCreatedAt(v time.Time) *StatusPageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StatusPageCreate) SetNillableCreatedAt(v *time.Time) *StatusPageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StatusPageCreate) SetUpdatedAt(v time.Time) *StatusPageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StatusPageCreate) SetNillableUpdatedAt(v *time.Time) *StatusPageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *StatusPageCreate) SetDeletedAt(v time.Time) *StatusPageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *StatusPageCreate) SetNillableDeletedAt(v *time.Time) *StatusPageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTagID sets the "tag_id" field.
func (_c *StatusPageCreate) SetTagID(v int) *StatusPageCreate {
	_c.mutation.SetTagID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *StatusPageCreate) SetName(v string) *StatusPageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *StatusPageCreate) SetIsPublic(v bool) *StatusPageCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *StatusPageCreate) SetNillableIsPublic(v *bool) *StatusPageCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetTag sets the "tag" edge to the Tag entity.
func (_c *StatusPageCreate) SetTag(v *Tag) *StatusPageCreate {
	return _c.SetTagID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the StatusMessage entity by IDs.
func (_c *StatusPageCreate) AddMessageIDs(ids ...int) *StatusPageCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the StatusMessage entity.
func (_c *StatusPageCreate) AddMessages(v ...*StatusMessage) *StatusPageCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the StatusPageMutation object of the builder.
func (_c *StatusPageCreate) Mutation() *StatusPageMutation {
	return _c.mutation
}

// Save creates the StatusPage in the database.
func (_c *StatusPageCreate) Save(ctx context.Context) (*StatusPage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StatusPageCreate) SaveX(ctx context.Context) *StatusPage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusPageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusPageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StatusPageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := statuspage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := statuspage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := statuspage.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StatusPageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StatusPage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StatusPage.updated_at"`)}
	}
	if _, ok := _c.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "StatusPage.tag_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StatusPage.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := statuspage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPage.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "StatusPage.is_public"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "StatusPage.tag"`)}
	}
	return nil
}

func (_c *StatusPageCreate) sqlSave(ctx context.Context) (*StatusPage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StatusPageCreate) createSpec() (*StatusPage, *sqlgraph.CreateSpec) {
	var (
		_node = &StatusPage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(statuspage.Table, sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(statuspage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(statuspage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(statuspage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(statuspage.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspage.TagTable,
			Columns: []string{statuspage.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.MessagesTable,
			Columns: []string{statuspage.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StatusPageCreateBulk is the builder for creating many StatusPage entities in bulk.
type StatusPageCreateBulk struct {
	config
	err      error
	builders []*StatusPageCreate
}

// Save creates the StatusPage entities in the database.
func (_c *StatusPageCreateBulk) Save(ctx context.Context) ([]*StatusPage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StatusPage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StatusPageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StatusPageCreateBulk) SaveX(ctx context.Context) []*StatusPage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusPageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusPageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
