// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/predicate"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statusmessage"
	"github.com/Phoenix-Uptime/phoenix-go/ent/statuspage"
)

// StatusMessageUpdate is the builder for updating StatusMessage entities.
type StatusMessageUpdate struct {
	config
	hooks    []Hook
	mutation *StatusMessageMutation
}

// Where appends a list predicates to the StatusMessageUpdate builder.
func (_u *StatusMessageUpdate) Where(ps ...predicate.StatusMessage) *StatusMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusMessageUpdate) SetUpdatedAt(v time.Time) *StatusMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StatusMessageUpdate) SetDeletedAt(v time.Time) *StatusMessageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StatusMessageUpdate) SetNillableDeletedAt(v *time.Time) *StatusMessageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StatusMessageUpdate) ClearDeletedAt() *StatusMessageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStatusPageID sets the "status_page_id" field.
func (_u *StatusMessageUpdate) SetStatusPageID(v int) *StatusMessageUpdate {
	_u.mutation.SetStatusPageID(v)
	return _u
}

// SetNillableStatusPageID sets the "status_page_id" field if the given value is not nil.
func (_u *StatusMessageUpdate) SetNillableStatusPageID(v *int) *StatusMessageUpdate {
	if v != nil {
		_u.SetStatusPageID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StatusMessageUpdate) SetParentID(v int) *StatusMessageUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StatusMessageUpdate) SetNillableParentID(v *int) *StatusMessageUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *StatusMessageUpdate) ClearParentID() *StatusMessageUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *StatusMessageUpdate) SetType(v statusmessage.Type) *StatusMessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StatusMessageUpdate) SetNillableType(v *statusmessage.Type) *StatusMessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *StatusMessageUpdate) SetContent(v string) *StatusMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *StatusMessageUpdate) SetNillableContent(v *string) *StatusMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatusPage sets the "status_page" edge to the StatusPage entity.
func (_u *StatusMessageUpdate) SetStatusPage(v *StatusPage) *StatusMessageUpdate {
	return _u.SetStatusPageID(v.ID)
}

// SetParent sets the "parent" edge to the StatusMessage entity.
func (_u *StatusMessageUpdate) SetParent(v *StatusMessage) *StatusMessageUpdate {
	return _u.SetParentID(v.ID)
}

// AddSubMessageIDs adds the "sub_messages" edge to the StatusMessage entity by IDs.
func (_u *StatusMessageUpdate) AddSubMessageIDs(ids ...int) *StatusMessageUpdate {
	_u.mutation.AddSubMessageIDs(ids...)
	return _u
}

// AddSubMessages adds the "sub_messages" edges to the StatusMessage entity.
func (_u *StatusMessageUpdate) AddSubMessages(v ...*StatusMessage) *StatusMessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubMessageIDs(ids...)
}

// Mutation returns the StatusMessageMutation object of the builder.
func (_u *StatusMessageUpdate) Mutation() *StatusMessageMutation {
	return _u.mutation
}

// ClearStatusPage clears the "status_page" edge to the StatusPage entity.
func (_u *StatusMessageUpdate) ClearStatusPage() *StatusMessageUpdate {
	_u.mutation.ClearStatusPage()
	return _u
}

// ClearParent clears the "parent" edge to the StatusMessage entity.
func (_u *StatusMessageUpdate) ClearParent() *StatusMessageUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearSubMessages clears all "sub_messages" edges to the StatusMessage entity.
func (_u *StatusMessageUpdate) ClearSubMessages() *StatusMessageUpdate {
	_u.mutation.ClearSubMessages()
	return _u
}

// RemoveSubMessageIDs removes the "sub_messages" edge to StatusMessage entities by IDs.
func (_u *StatusMessageUpdate) RemoveSubMessageIDs(ids ...int) *StatusMessageUpdate {
	_u.mutation.RemoveSubMessageIDs(ids...)
	return _u
}

// RemoveSubMessages removes "sub_messages" edges to StatusMessage entities.
func (_u *StatusMessageUpdate) RemoveSubMessages(v ...*StatusMessage) *StatusMessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statusmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusMessageUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := statusmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StatusMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := statusmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "StatusMessage.content": %w`, err)}
		}
	}
	if _u.mutation.StatusPageCleared() && len(_u.mutation.StatusPageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusMessage.status_page"`)
	}
	return nil
}

func (_u *StatusMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statusmessage.Table, statusmessage.Columns, sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statusmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(statusmessage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(statusmessage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(statusmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(statusmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.StatusPageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.StatusPageTable,
			Columns: []string{statusmessage.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.StatusPageTable,
			Columns: []string{statusmessage.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.ParentTable,
			Columns: []string{statusmessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.ParentTable,
			Columns: []string{statusmessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubMessagesIDs(); len(nodes) > 0 && !_u.mutation.SubMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusMessageUpdateOne is the builder for updating a single StatusMessage entity.
type StatusMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusMessageUpdateOne) SetUpdatedAt(v time.Time) *StatusMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StatusMessageUpdateOne) SetDeletedAt(v time.Time) *StatusMessageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StatusMessageUpdateOne) SetNillableDeletedAt(v *time.Time) *StatusMessageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StatusMessageUpdateOne) ClearDeletedAt() *StatusMessageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStatusPageID sets the "status_page_id" field.
func (_u *StatusMessageUpdateOne) SetStatusPageID(v int) *StatusMessageUpdateOne {
	_u.mutation.SetStatusPageID(v)
	return _u
}

// SetNillableStatusPageID sets the "status_page_id" field if the given value is not nil.
func (_u *StatusMessageUpdateOne) SetNillableStatusPageID(v *int) *StatusMessageUpdateOne {
	if v != nil {
		_u.SetStatusPageID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *StatusMessageUpdateOne) SetParentID(v int) *StatusMessageUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *StatusMessageUpdateOne) SetNillableParentID(v *int) *StatusMessageUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *StatusMessageUpdateOne) ClearParentID() *StatusMessageUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *StatusMessageUpdateOne) SetType(v statusmessage.Type) *StatusMessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *StatusMessageUpdateOne) SetNillableType(v *statusmessage.Type) *StatusMessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *StatusMessageUpdateOne) SetContent(v string) *StatusMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *StatusMessageUpdateOne) SetNillableContent(v *string) *StatusMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatusPage sets the "status_page" edge to the StatusPage entity.
func (_u *StatusMessageUpdateOne) SetStatusPage(v *StatusPage) *StatusMessageUpdateOne {
	return _u.SetStatusPageID(v.ID)
}

// SetParent sets the "parent" edge to the StatusMessage entity.
func (_u *StatusMessageUpdateOne) SetParent(v *StatusMessage) *StatusMessageUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddSubMessageIDs adds the "sub_messages" edge to the StatusMessage entity by IDs.
func (_u *StatusMessageUpdateOne) AddSubMessageIDs(ids ...int) *StatusMessageUpdateOne {
	_u.mutation.AddSubMessageIDs(ids...)
	return _u
}

// AddSubMessages adds the "sub_messages" edges to the StatusMessage entity.
func (_u *StatusMessageUpdateOne) AddSubMessages(v ...*StatusMessage) *StatusMessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubMessageIDs(ids...)
}

// Mutation returns the StatusMessageMutation object of the builder.
func (_u *StatusMessageUpdateOne) Mutation() *StatusMessageMutation {
	return _u.mutation
}

// ClearStatusPage clears the "status_page" edge to the StatusPage entity.
func (_u *StatusMessageUpdateOne) ClearStatusPage() *StatusMessageUpdateOne {
	_u.mutation.ClearStatusPage()
	return _u
}

// ClearParent clears the "parent" edge to the StatusMessage entity.
func (_u *StatusMessageUpdateOne) ClearParent() *StatusMessageUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearSubMessages clears all "sub_messages" edges to the StatusMessage entity.
func (_u *StatusMessageUpdateOne) ClearSubMessages() *StatusMessageUpdateOne {
	_u.mutation.ClearSubMessages()
	return _u
}

// RemoveSubMessageIDs removes the "sub_messages" edge to StatusMessage entities by IDs.
func (_u *StatusMessageUpdateOne) RemoveSubMessageIDs(ids ...int) *StatusMessageUpdateOne {
	_u.mutation.RemoveSubMessageIDs(ids...)
	return _u
}

// RemoveSubMessages removes "sub_messages" edges to StatusMessage entities.
func (_u *StatusMessageUpdateOne) RemoveSubMessages(v ...*StatusMessage) *StatusMessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubMessageIDs(ids...)
}

// Where appends a list predicates to the StatusMessageUpdate builder.
func (_u *StatusMessageUpdateOne) Where(ps ...predicate.StatusMessage) *StatusMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusMessageUpdateOne) Select(field string, fields ...string) *StatusMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StatusMessage entity.
func (_u *StatusMessageUpdateOne) Save(ctx context.Context) (*StatusMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusMessageUpdateOne) SaveX(ctx context.Context) *StatusMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statusmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusMessageUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := statusmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StatusMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := statusmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "StatusMessage.content": %w`, err)}
		}
	}
	if _u.mutation.StatusPageCleared() && len(_u.mutation.StatusPageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusMessage.status_page"`)
	}
	return nil
}

func (_u *StatusMessageUpdateOne) sqlSave(ctx context.Context) (_node *StatusMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statusmessage.Table, statusmessage.Columns, sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatusMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statusmessage.FieldID)
		for _, f := range fields {
			if !statusmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statusmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statusmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(statusmessage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(statusmessage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(statusmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(statusmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.StatusPageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.StatusPageTable,
			Columns: []string{statusmessage.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.StatusPageTable,
			Columns: []string{statusmessage.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.ParentTable,
			Columns: []string{statusmessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statusmessage.ParentTable,
			Columns: []string{statusmessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubMessagesIDs(); len(nodes) > 0 && !_u.mutation.SubMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statusmessage.SubMessagesTable,
			Columns: []string{statusmessage.SubMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statusmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StatusMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
