// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Phoenix-Uptime/phoenix-go/ent/monitor"
	"github.com/Phoenix-Uptime/phoenix-go/ent/predicate"
	"github.com/Phoenix-Uptime/phoenix-go/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdate) SetDeletedAt(v time.Time) *UserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDeletedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdate) ClearDeletedAt() *UserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdate) SetAPIKey(v string) *UserUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAPIKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSMTPSMTPServer sets the "smtp_smtp_server" field.
func (_u *UserUpdate) SetSMTPSMTPServer(v string) *UserUpdate {
	_u.mutation.SetSMTPSMTPServer(v)
	return _u
}

// SetNillableSMTPSMTPServer sets the "smtp_smtp_server" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPSMTPServer(v *string) *UserUpdate {
	if v != nil {
		_u.SetSMTPSMTPServer(*v)
	}
	return _u
}

// ClearSMTPSMTPServer clears the value of the "smtp_smtp_server" field.
func (_u *UserUpdate) ClearSMTPSMTPServer() *UserUpdate {
	_u.mutation.ClearSMTPSMTPServer()
	return _u
}

// SetSMTPSMTPPort sets the "smtp_smtp_port" field.
func (_u *UserUpdate) SetSMTPSMTPPort(v int) *UserUpdate {
	_u.mutation.ResetSMTPSMTPPort()
	_u.mutation.SetSMTPSMTPPort(v)
	return _u
}

// SetNillableSMTPSMTPPort sets the "smtp_smtp_port" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPSMTPPort(v *int) *UserUpdate {
	if v != nil {
		_u.SetSMTPSMTPPort(*v)
	}
	return _u
}

// AddSMTPSMTPPort adds value to the "smtp_smtp_port" field.
func (_u *UserUpdate) AddSMTPSMTPPort(v int) *UserUpdate {
	_u.mutation.AddSMTPSMTPPort(v)
	return _u
}

// ClearSMTPSMTPPort clears the value of the "smtp_smtp_port" field.
func (_u *UserUpdate) ClearSMTPSMTPPort() *UserUpdate {
	_u.mutation.ClearSMTPSMTPPort()
	return _u
}

// SetSMTPFromAddress sets the "smtp_from_address" field.
func (_u *UserUpdate) SetSMTPFromAddress(v string) *UserUpdate {
	_u.mutation.SetSMTPFromAddress(v)
	return _u
}

// SetNillableSMTPFromAddress sets the "smtp_from_address" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPFromAddress(v *string) *UserUpdate {
	if v != nil {
		_u.SetSMTPFromAddress(*v)
	}
	return _u
}

// ClearSMTPFromAddress clears the value of the "smtp_from_address" field.
func (_u *UserUpdate) ClearSMTPFromAddress() *UserUpdate {
	_u.mutation.ClearSMTPFromAddress()
	return _u
}

// SetSMTPUsername sets the "smtp_username" field.
func (_u *UserUpdate) SetSMTPUsername(v string) *UserUpdate {
	_u.mutation.SetSMTPUsername(v)
	return _u
}

// SetNillableSMTPUsername sets the "smtp_username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetSMTPUsername(*v)
	}
	return _u
}

// ClearSMTPUsername clears the value of the "smtp_username" field.
func (_u *UserUpdate) ClearSMTPUsername() *UserUpdate {
	_u.mutation.ClearSMTPUsername()
	return _u
}

// SetSMTPPassword sets the "smtp_password" field.
func (_u *UserUpdate) SetSMTPPassword(v string) *UserUpdate {
	_u.mutation.SetSMTPPassword(v)
	return _u
}

// SetNillableSMTPPassword sets the "smtp_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPPassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetSMTPPassword(*v)
	}
	return _u
}

// ClearSMTPPassword clears the value of the "smtp_password" field.
func (_u *UserUpdate) ClearSMTPPassword() *UserUpdate {
	_u.mutation.ClearSMTPPassword()
	return _u
}

// SetSMTPUseTLS sets the "smtp_use_tls" field.
func (_u *UserUpdate) SetSMTPUseTLS(v bool) *UserUpdate {
	_u.mutation.SetSMTPUseTLS(v)
	return _u
}

// SetNillableSMTPUseTLS sets the "smtp_use_tls" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSMTPUseTLS(v *bool) *UserUpdate {
	if v != nil {
		_u.SetSMTPUseTLS(*v)
	}
	return _u
}

// ClearSMTPUseTLS clears the value of the "smtp_use_tls" field.
func (_u *UserUpdate) ClearSMTPUseTLS() *UserUpdate {
	_u.mutation.ClearSMTPUseTLS()
	return _u
}

// SetTelegramBotToken sets the "telegram_bot_token" field.
func (_u *UserUpdate) SetTelegramBotToken(v string) *UserUpdate {
	_u.mutation.SetTelegramBotToken(v)
	return _u
}

// SetNillableTelegramBotToken sets the "telegram_bot_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTelegramBotToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetTelegramBotToken(*v)
	}
	return _u
}

// ClearTelegramBotToken clears the value of the "telegram_bot_token" field.
func (_u *UserUpdate) ClearTelegramBotToken() *UserUpdate {
	_u.mutation.ClearTelegramBotToken()
	return _u
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (_u *UserUpdate) AddMonitorIDs(ids ...int) *UserUpdate {
	_u.mutation.AddMonitorIDs(ids...)
	return _u
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (_u *UserUpdate) AddMonitors(v ...*Monitor) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonitorIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (_u *UserUpdate) ClearMonitors() *UserUpdate {
	_u.mutation.ClearMonitors()
	return _u
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (_u *UserUpdate) RemoveMonitorIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveMonitorIDs(ids...)
	return _u
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (_u *UserUpdate) RemoveMonitors(v ...*Monitor) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonitorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := user.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "User.api_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SMTPSMTPServer(); ok {
		_spec.SetField(user.FieldSMTPSMTPServer, field.TypeString, value)
	}
	if _u.mutation.SMTPSMTPServerCleared() {
		_spec.ClearField(user.FieldSMTPSMTPServer, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPSMTPPort(); ok {
		_spec.SetField(user.FieldSMTPSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSMTPSMTPPort(); ok {
		_spec.AddField(user.FieldSMTPSMTPPort, field.TypeInt, value)
	}
	if _u.mutation.SMTPSMTPPortCleared() {
		_spec.ClearField(user.FieldSMTPSMTPPort, field.TypeInt)
	}
	if value, ok := _u.mutation.SMTPFromAddress(); ok {
		_spec.SetField(user.FieldSMTPFromAddress, field.TypeString, value)
	}
	if _u.mutation.SMTPFromAddressCleared() {
		_spec.ClearField(user.FieldSMTPFromAddress, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPUsername(); ok {
		_spec.SetField(user.FieldSMTPUsername, field.TypeString, value)
	}
	if _u.mutation.SMTPUsernameCleared() {
		_spec.ClearField(user.FieldSMTPUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPPassword(); ok {
		_spec.SetField(user.FieldSMTPPassword, field.TypeString, value)
	}
	if _u.mutation.SMTPPasswordCleared() {
		_spec.ClearField(user.FieldSMTPPassword, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPUseTLS(); ok {
		_spec.SetField(user.FieldSMTPUseTLS, field.TypeBool, value)
	}
	if _u.mutation.SMTPUseTLSCleared() {
		_spec.ClearField(user.FieldSMTPUseTLS, field.TypeBool)
	}
	if value, ok := _u.mutation.TelegramBotToken(); ok {
		_spec.SetField(user.FieldTelegramBotToken, field.TypeString, value)
	}
	if _u.mutation.TelegramBotTokenCleared() {
		_spec.ClearField(user.FieldTelegramBotToken, field.TypeString)
	}
	if _u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !_u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdateOne) SetDeletedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDeletedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdateOne) ClearDeletedAt() *UserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdateOne) SetAPIKey(v string) *UserUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAPIKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetSMTPSMTPServer sets the "smtp_smtp_server" field.
func (_u *UserUpdateOne) SetSMTPSMTPServer(v string) *UserUpdateOne {
	_u.mutation.SetSMTPSMTPServer(v)
	return _u
}

// SetNillableSMTPSMTPServer sets the "smtp_smtp_server" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPSMTPServer(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPSMTPServer(*v)
	}
	return _u
}

// ClearSMTPSMTPServer clears the value of the "smtp_smtp_server" field.
func (_u *UserUpdateOne) ClearSMTPSMTPServer() *UserUpdateOne {
	_u.mutation.ClearSMTPSMTPServer()
	return _u
}

// SetSMTPSMTPPort sets the "smtp_smtp_port" field.
func (_u *UserUpdateOne) SetSMTPSMTPPort(v int) *UserUpdateOne {
	_u.mutation.ResetSMTPSMTPPort()
	_u.mutation.SetSMTPSMTPPort(v)
	return _u
}

// SetNillableSMTPSMTPPort sets the "smtp_smtp_port" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPSMTPPort(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPSMTPPort(*v)
	}
	return _u
}

// AddSMTPSMTPPort adds value to the "smtp_smtp_port" field.
func (_u *UserUpdateOne) AddSMTPSMTPPort(v int) *UserUpdateOne {
	_u.mutation.AddSMTPSMTPPort(v)
	return _u
}

// ClearSMTPSMTPPort clears the value of the "smtp_smtp_port" field.
func (_u *UserUpdateOne) ClearSMTPSMTPPort() *UserUpdateOne {
	_u.mutation.ClearSMTPSMTPPort()
	return _u
}

// SetSMTPFromAddress sets the "smtp_from_address" field.
func (_u *UserUpdateOne) SetSMTPFromAddress(v string) *UserUpdateOne {
	_u.mutation.SetSMTPFromAddress(v)
	return _u
}

// SetNillableSMTPFromAddress sets the "smtp_from_address" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPFromAddress(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPFromAddress(*v)
	}
	return _u
}

// ClearSMTPFromAddress clears the value of the "smtp_from_address" field.
func (_u *UserUpdateOne) ClearSMTPFromAddress() *UserUpdateOne {
	_u.mutation.ClearSMTPFromAddress()
	return _u
}

// SetSMTPUsername sets the "smtp_username" field.
func (_u *UserUpdateOne) SetSMTPUsername(v string) *UserUpdateOne {
	_u.mutation.SetSMTPUsername(v)
	return _u
}

// SetNillableSMTPUsername sets the "smtp_username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPUsername(*v)
	}
	return _u
}

// ClearSMTPUsername clears the value of the "smtp_username" field.
func (_u *UserUpdateOne) ClearSMTPUsername() *UserUpdateOne {
	_u.mutation.ClearSMTPUsername()
	return _u
}

// SetSMTPPassword sets the "smtp_password" field.
func (_u *UserUpdateOne) SetSMTPPassword(v string) *UserUpdateOne {
	_u.mutation.SetSMTPPassword(v)
	return _u
}

// SetNillableSMTPPassword sets the "smtp_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPPassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPPassword(*v)
	}
	return _u
}

// ClearSMTPPassword clears the value of the "smtp_password" field.
func (_u *UserUpdateOne) ClearSMTPPassword() *UserUpdateOne {
	_u.mutation.ClearSMTPPassword()
	return _u
}

// SetSMTPUseTLS sets the "smtp_use_tls" field.
func (_u *UserUpdateOne) SetSMTPUseTLS(v bool) *UserUpdateOne {
	_u.mutation.SetSMTPUseTLS(v)
	return _u
}

// SetNillableSMTPUseTLS sets the "smtp_use_tls" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSMTPUseTLS(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetSMTPUseTLS(*v)
	}
	return _u
}

// ClearSMTPUseTLS clears the value of the "smtp_use_tls" field.
func (_u *UserUpdateOne) ClearSMTPUseTLS() *UserUpdateOne {
	_u.mutation.ClearSMTPUseTLS()
	return _u
}

// SetTelegramBotToken sets the "telegram_bot_token" field.
func (_u *UserUpdateOne) SetTelegramBotToken(v string) *UserUpdateOne {
	_u.mutation.SetTelegramBotToken(v)
	return _u
}

// SetNillableTelegramBotToken sets the "telegram_bot_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTelegramBotToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTelegramBotToken(*v)
	}
	return _u
}

// ClearTelegramBotToken clears the value of the "telegram_bot_token" field.
func (_u *UserUpdateOne) ClearTelegramBotToken() *UserUpdateOne {
	_u.mutation.ClearTelegramBotToken()
	return _u
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (_u *UserUpdateOne) AddMonitorIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddMonitorIDs(ids...)
	return _u
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (_u *UserUpdateOne) AddMonitors(v ...*Monitor) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonitorIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (_u *UserUpdateOne) ClearMonitors() *UserUpdateOne {
	_u.mutation.ClearMonitors()
	return _u
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (_u *UserUpdateOne) RemoveMonitorIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveMonitorIDs(ids...)
	return _u
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (_u *UserUpdateOne) RemoveMonitors(v ...*Monitor) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonitorIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := user.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "User.api_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SMTPSMTPServer(); ok {
		_spec.SetField(user.FieldSMTPSMTPServer, field.TypeString, value)
	}
	if _u.mutation.SMTPSMTPServerCleared() {
		_spec.ClearField(user.FieldSMTPSMTPServer, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPSMTPPort(); ok {
		_spec.SetField(user.FieldSMTPSMTPPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSMTPSMTPPort(); ok {
		_spec.AddField(user.FieldSMTPSMTPPort, field.TypeInt, value)
	}
	if _u.mutation.SMTPSMTPPortCleared() {
		_spec.ClearField(user.FieldSMTPSMTPPort, field.TypeInt)
	}
	if value, ok := _u.mutation.SMTPFromAddress(); ok {
		_spec.SetField(user.FieldSMTPFromAddress, field.TypeString, value)
	}
	if _u.mutation.SMTPFromAddressCleared() {
		_spec.ClearField(user.FieldSMTPFromAddress, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPUsername(); ok {
		_spec.SetField(user.FieldSMTPUsername, field.TypeString, value)
	}
	if _u.mutation.SMTPUsernameCleared() {
		_spec.ClearField(user.FieldSMTPUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPPassword(); ok {
		_spec.SetField(user.FieldSMTPPassword, field.TypeString, value)
	}
	if _u.mutation.SMTPPasswordCleared() {
		_spec.ClearField(user.FieldSMTPPassword, field.TypeString)
	}
	if value, ok := _u.mutation.SMTPUseTLS(); ok {
		_spec.SetField(user.FieldSMTPUseTLS, field.TypeBool, value)
	}
	if _u.mutation.SMTPUseTLSCleared() {
		_spec.ClearField(user.FieldSMTPUseTLS, field.TypeBool)
	}
	if value, ok := _u.mutation.TelegramBotToken(); ok {
		_spec.SetField(user.FieldTelegramBotToken, field.TypeString, value)
	}
	if _u.mutation.TelegramBotTokenCleared() {
		_spec.ClearField(user.FieldTelegramBotToken, field.TypeString)
	}
	if _u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !_u.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MonitorsTable,
			Columns: []string{user.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
