// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMonitors holds the string denoting the monitors edge name in mutations.
	EdgeMonitors = "monitors"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeNotificationChannels holds the string denoting the notification_channels edge name in mutations.
	EdgeNotificationChannels = "notification_channels"
	// EdgeAlertRules holds the string denoting the alert_rules edge name in mutations.
	EdgeAlertRules = "alert_rules"
	// EdgeStatusPages holds the string denoting the status_pages edge name in mutations.
	EdgeStatusPages = "status_pages"
	// EdgeMaintenanceWindows holds the string denoting the maintenance_windows edge name in mutations.
	EdgeMaintenanceWindows = "maintenance_windows"
	// EdgeResolvedIncidents holds the string denoting the resolved_incidents edge name in mutations.
	EdgeResolvedIncidents = "resolved_incidents"
	// Table holds the table name of the user in the database.
	Table = "users"
	// MonitorsTable is the table that holds the monitors relation/edge.
	MonitorsTable = "monitors"
	// MonitorsInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorsInverseTable = "monitors"
	// MonitorsColumn is the table column denoting the monitors relation/edge.
	MonitorsColumn = "user_id"
	// TagsTable is the table that holds the tags relation/edge.
	TagsTable = "tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// TagsColumn is the table column denoting the tags relation/edge.
	TagsColumn = "user_id"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "user_id"
	// NotificationChannelsTable is the table that holds the notification_channels relation/edge.
	NotificationChannelsTable = "notification_channels"
	// NotificationChannelsInverseTable is the table name for the NotificationChannel entity.
	// It exists in this package in order to avoid circular dependency with the "notificationchannel" package.
	NotificationChannelsInverseTable = "notification_channels"
	// NotificationChannelsColumn is the table column denoting the notification_channels relation/edge.
	NotificationChannelsColumn = "user_id"
	// AlertRulesTable is the table that holds the alert_rules relation/edge.
	AlertRulesTable = "alert_rules"
	// AlertRulesInverseTable is the table name for the AlertRule entity.
	// It exists in this package in order to avoid circular dependency with the "alertrule" package.
	AlertRulesInverseTable = "alert_rules"
	// AlertRulesColumn is the table column denoting the alert_rules relation/edge.
	AlertRulesColumn = "user_id"
	// StatusPagesTable is the table that holds the status_pages relation/edge.
	StatusPagesTable = "status_pages"
	// StatusPagesInverseTable is the table name for the StatusPage entity.
	// It exists in this package in order to avoid circular dependency with the "statuspage" package.
	StatusPagesInverseTable = "status_pages"
	// StatusPagesColumn is the table column denoting the status_pages relation/edge.
	StatusPagesColumn = "user_id"
	// MaintenanceWindowsTable is the table that holds the maintenance_windows relation/edge.
	MaintenanceWindowsTable = "maintenance_windows"
	// MaintenanceWindowsInverseTable is the table name for the MaintenanceWindow entity.
	// It exists in this package in order to avoid circular dependency with the "maintenancewindow" package.
	MaintenanceWindowsInverseTable = "maintenance_windows"
	// MaintenanceWindowsColumn is the table column denoting the maintenance_windows relation/edge.
	MaintenanceWindowsColumn = "user_id"
	// ResolvedIncidentsTable is the table that holds the resolved_incidents relation/edge.
	ResolvedIncidentsTable = "incidents"
	// ResolvedIncidentsInverseTable is the table name for the Incident entity.
	// It exists in this package in order to avoid circular dependency with the "incident" package.
	ResolvedIncidentsInverseTable = "incidents"
	// ResolvedIncidentsColumn is the table column denoting the resolved_incidents relation/edge.
	ResolvedIncidentsColumn = "resolved_by_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEmail,
	FieldPassword,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMonitorsCount orders the results by monitors count.
func ByMonitorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMonitorsStep(), opts...)
	}
}

// ByMonitors orders the results by monitors terms.
func ByMonitors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationChannelsCount orders the results by notification_channels count.
func ByNotificationChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationChannelsStep(), opts...)
	}
}

// ByNotificationChannels orders the results by notification_channels terms.
func ByNotificationChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAlertRulesCount orders the results by alert_rules count.
func ByAlertRulesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAlertRulesStep(), opts...)
	}
}

// ByAlertRules orders the results by alert_rules terms.
func ByAlertRules(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAlertRulesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStatusPagesCount orders the results by status_pages count.
func ByStatusPagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatusPagesStep(), opts...)
	}
}

// ByStatusPages orders the results by status_pages terms.
func ByStatusPages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatusPagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMaintenanceWindowsCount orders the results by maintenance_windows count.
func ByMaintenanceWindowsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMaintenanceWindowsStep(), opts...)
	}
}

// ByMaintenanceWindows orders the results by maintenance_windows terms.
func ByMaintenanceWindows(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMaintenanceWindowsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResolvedIncidentsCount orders the results by resolved_incidents count.
func ByResolvedIncidentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResolvedIncidentsStep(), opts...)
	}
}

// ByResolvedIncidents orders the results by resolved_incidents terms.
func ByResolvedIncidents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResolvedIncidentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMonitorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MonitorsTable, MonitorsColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TagsTable, TagsColumn),
	)
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newNotificationChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationChannelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationChannelsTable, NotificationChannelsColumn),
	)
}
func newAlertRulesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AlertRulesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AlertRulesTable, AlertRulesColumn),
	)
}
func newStatusPagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatusPagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StatusPagesTable, StatusPagesColumn),
	)
}
func newMaintenanceWindowsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MaintenanceWindowsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MaintenanceWindowsTable, MaintenanceWindowsColumn),
	)
}
func newResolvedIncidentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResolvedIncidentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResolvedIncidentsTable, ResolvedIncidentsColumn),
	)
}
